### PR TITLE
FIX: Enum Entities codes are trimmed after getting from db

### PR DESCRIPTION
**Pull request by denys-davydov**

### CODE REVIEW

**Comment by dmytro-palczewski-osi** [comment]
Why not do it by hibernate, @ColumnTransformer(read = "trim(...)")?

**Comment by dmytro-palczewski-osi** [comment]
isEmptyString() method shoud be renamed to isBlankString()
isEmptyCharacter() method should be renamed to isSpaceCharacter()
normalizeCode() to trimCode()

**Comment by dmytro-palczewski-osi** [comment]
Add please a unit test for this functionality

**Comment by denys-davydov** [comment]
@dmytro-palczewski-osi Dmytro, I totally agree with your renaming propositions, everything is renamed as you requested. Added unit tests on all #convertToEntityAttribute() cases.

**Pull request merged**
