### PR TITLE
NEW: TPT3-59. Added Address (ADDRS_T), Client Address (CL_ADDRT) and …

### PR DESCRIPTION
**Pull request by denys-davydov**
…another version of SystemCode (SYS_CD_C) entities and respective DAO to legacy-data-access module

### CODE REVIEW

**Comment by dmytro-palczewski-osi** [comment]
There is base class for entities CmsPersistentObject which contains default implementation for equlas() and hashCode()

**Comment by dmytro-palczewski-osi** [comment]
Do we really need mark   getPrimaryKey() method as @Transient?

**Comment by dmytro-palczewski-osi** [comment]
We have alredy entity SystemCodeTable mapped on "SYS_CD_C" table. Why do we need another one (SystemCode)?

**Comment by dmytro-palczewski-osi** [comment]
I doubt that it's a good idea to extend NullPointerException since our exception logically is not a NullPointerException because it is not thrown always when pointer is null but when object exists but is empty as well. I propose to extend RuntimeException.

**Comment by dmytro-palczewski-osi** [comment]
private String fkAddress;
private String fkClient; 
private String fkReferral;

foreign keys should be mapped to corresponding entities.

**Comment by denys-davydov** [comment]
Thank you @dmytro-palczewski-osi . My entities now extend CmsPersistentObject, getPrimaryKey() is not annotated with "@Transient" and NullOrEmptyException extends RuntimeException.

**Comment by dmytro-palczewski-osi** [comment]
I still insist that having two entities mapped to the same SYS_CD_C table is a bad idea.
If the only reason to create new SystemCode entity was a possibility to create query by fkMeta field we may do it just by creating only new generic DAO class and use hibernate polymorphic query "from SystemCode sc WHERE sc.fkMeta = :"

**Pull request merged**
